// Snapshot of the site's launch content used to seed an empty database.
// Icons are stored as lucide export-name strings (resolved on the client).

export const hero = {
  eyebrow: 'Global Logistics Solutions',
  heading: 'Global Trade, Logistics & Supply Chain Solutions',
  subheading:
    'Import • Export • Trading • Transportation • Freight Forwarding Worldwide',
};

export const offices = [
  {
    id: 'chandigarh',
    type: 'Corporate Office',
    name: 'Highority India Pvt Ltd',
    address:
      'Unit 1408, 14th Floor, Chandigarh Citi Center (CCC), VIP Road, Zirakpur, Punjab – 140603',
    city: 'Chandigarh',
    phones: ['+91-70870-87333', '01762-500046'],
    emails: ['contact@highority.in'],
    mapQuery: 'Chandigarh+Citi+Center+Zirakpur',
    cityImage: '/assets/city-chandigarh.jpg',
    icon: 'Navigation',
  },
  {
    id: 'ahmedabad',
    type: 'Branch Office',
    name: 'Highority India Pvt Ltd',
    address:
      'C-401-402, 4th Floor, Supath-2 Complex, Opp. Holiday Inn Express Hotel, Near Old Vadaj Bus Stand, Usmanpura, Ashram Road, Ahmedabad – 380013',
    city: 'Ahmedabad',
    phones: ['+91-70870-87333'],
    emails: ['contact@highority.in'],
    mapQuery: 'Supath+2+Complex+Ashram+Road+Ahmedabad',
    cityImage: '/assets/city-ahmedabad.jpg',
    icon: 'MapPin',
  },
  {
    id: 'delhi',
    type: 'Branch Office',
    name: 'Highority India Pvt Ltd',
    address: '333/1, G.P. Mahipalpur, Rangpuri, New Delhi – 110037',
    city: 'Delhi',
    phones: ['+91-70870-87333'],
    emails: ['contact@highority.in'],
    mapQuery: 'Mahipalpur+Rangpuri+New+Delhi',
    cityImage: '/assets/city-delhi.jpg',
    icon: 'MapPin',
  },
  {
    id: 'jaipur',
    type: 'Branch Office',
    name: 'Highority India Pvt Ltd',
    address:
      'Shop No. B-07, Ghar Aangan, Village Hajyawala, Sanganer, Jaipur, Rajasthan – 302029',
    city: 'Jaipur',
    phones: ['+91-70870-87333'],
    emails: ['contact@highority.in'],
    mapQuery: 'Ghar+Aangan+Sanganer+Jaipur',
    cityImage: '/assets/city-jaipur.jpg',
    icon: 'MapPin',
  },
  {
    id: 'dubai',
    type: 'UAE Office',
    name: 'HIGHORITY IMPEX TRADING L.L.C',
    address:
      '006, 1st Floor, Unique Time Business Center, Union Coop, Al Aweer Central Market, Dubai, United Arab Emirates',
    city: 'Dubai',
    phones: ['+971-505059232', '+971-042597273'],
    emails: ['impex@highority.in'],
    mapQuery: 'Unique+Time+Business+Center+Al+Aweer+Dubai',
    cityImage: '/assets/city-dubai.jpg',
    icon: 'MapPin',
  },
];

export const certifications = [
  { id: 'iec', title: 'Importer Exporter Code Certificate', subtitle: 'IEC Registration', issuer: 'DGFT, Ministry of Commerce, Government of India', description: 'Registered Importer Exporter Code (IEC AAFCH3999D) enabling seamless import and export operations from India.', image: '/assets/cert-iec.jpg?v=2', icon: 'FileCheck' },
  { id: 'spices-board', title: 'Spices Board Registration Certificate', subtitle: 'Exporter of Spices', issuer: 'Spices Board of India', description: 'Authorized for the export of Indian spices, herbs, and spice products to global markets.', image: '/assets/cert-spices.jpg?v=2', icon: 'Leaf' },
  { id: 'dubai-chamber', title: 'Dubai Chamber Membership Certificate', subtitle: 'Corporate Membership', issuer: 'Dubai Chamber of Commerce', description: 'Highority Impex Trading LLC is a registered member authorized for trade across UAE and Middle East.', image: '/assets/cert-dubai.jpg?v=2', icon: 'Building2' },
  { id: 'aeo-t1', title: 'AEO T1 MSME Certificate', subtitle: 'Authorized Economic Operator', issuer: 'Indian Customs, CBIC', description: 'Tier 1 AEO certification for Importer & Exporter categories with priority customs clearance.', image: '/assets/cert-aeo.jpg?v=2', icon: 'ShieldCheck' },
  { id: 'trademark', title: 'Trademark Certificate', subtitle: 'Registered Trademark', issuer: 'Trade Marks Registry, Government of India', description: 'Registered trademark under Section 23(2) & Rule 56(1) protecting the Highority brand identity.', image: '/assets/cert-trademark.jpg?v=2', icon: 'BookmarkCheck' },
  { id: 'iso-9001', title: 'ISO 9001:2015 Certificate', subtitle: 'Quality Management System', issuer: 'International Standards Organization', description: 'Certified Quality Management System demonstrating commitment to consistent quality in logistics.', image: '/assets/cert-iso.jpg?v=2', icon: 'Award' },
  { id: 'iata', title: 'IATA Accreditation Certificate', subtitle: 'Air Transport Association', issuer: 'International Air Transport Association', description: 'Accredited for cargo agency operations enabling direct partnerships with airlines for air freight.', image: '/assets/cert-iata.jpg?v=2', icon: 'Plane' },
  { id: 'acfi', title: 'ACFI Membership Certificate', subtitle: 'Air Cargo Forum India', issuer: 'Air Cargo Forum India (ACFI)', description: 'Highority India Private Limited is a valued member of Air Cargo Forum India for F.Y. 2025–2026, strengthening our presence in the Indian air cargo community.', image: '/assets/cert-acfi.jpg?v=1', icon: 'Handshake' },
  { id: 'udyam', title: 'Udyam Registration Certificate', subtitle: 'MSME Registration', issuer: 'Ministry of MSME, Government of India', description: 'Registered Micro, Small and Medium Enterprise recognized by the Ministry of MSME.', image: '/assets/cert-udyam.jpg?v=2', icon: 'Factory' },
  { id: 'gst', title: 'GST Registration Certificate', subtitle: 'Goods & Services Tax', issuer: 'Goods and Services Tax Network, Government of India', description: 'Registered GST taxpayer (03AAFCH3999D1ZK) for Highority India Private Limited under regular registration.', image: '/assets/cert-gst.jpg?v=1', icon: 'Receipt' },
  { id: 'fssai', title: 'FSSAI License Certificate', subtitle: 'Food Safety License', issuer: 'Food Safety and Standards Authority of India', description: 'Licensed for handling, storage, and transportation of food products and perishable cargo.', image: '/assets/cert-fssai.jpg?v=2', icon: 'Utensils' },
];

export const companies = [
  {
    id: 'tk-transport',
    name: 'TK Transport Services India',
    tagline: "Driving India's Logistics Network",
    location: 'India',
    description:
      'TK Transport Services India is a leading logistics and transportation company specializing in Last Mile Delivery, Middle Mile Transportation, Warehousing, and Supply Chain Solutions. We work with e-commerce companies, retail businesses, manufacturers, and distributors to ensure fast, reliable, and cost-effective transportation services across India.',
    banner: '/assets/company-tk-transport.jpg',
    slug: 'tk-transport-services-india',
    services: ['Last Mile Delivery', 'Middle Mile Transportation', 'E-commerce Logistics', 'Warehousing & Distribution', 'Supply Chain Management', 'Full Truck Load (FTL)', 'Part Truck Load (PTL)', 'Express Cargo Services'],
    industries: ['E-commerce Companies', 'Retail Chains', 'FMCG Companies', 'Manufacturing Units', 'Distribution Networks'],
    markets: ['India'],
    icon: 'Truck',
    color: 'from-[#00D4FF] to-[#00A8CC]',
    email: null,
  },
  {
    id: 'highority-impex',
    name: 'Highority Impex Trading LLC',
    tagline: 'Global Trading & Procurement Solutions',
    location: 'United Arab Emirates',
    description:
      'Highority Impex Trading LLC is a UAE-based general trading company engaged in import, export, sourcing, and distribution of a wide range of products. The company connects manufacturers, suppliers, and buyers across international markets while ensuring quality products and competitive pricing.',
    banner: '/assets/company-highority-impex.jpg',
    slug: 'highority-impex-trading-llc',
    services: ['Import & Export', 'International Trading', 'Product Sourcing', 'Procurement Services', 'Distribution & Supply', 'Global Business Partnerships'],
    industries: ['Agro Products', 'Food & Non-Food Products', 'FMCG Products', 'Snacks & Confectionery', 'Household Products', 'Personal Care Products', 'General Trading Items', 'Industrial & Commercial Supplies'],
    markets: ['UAE', 'GCC Countries', 'Asia', 'Africa', 'Europe'],
    icon: 'Globe',
    color: 'from-[#00D4FF] to-[#0088AA]',
    email: 'impex@highority.in',
  },
  {
    id: 'highfive-global',
    name: 'HighFive Global Ltd.',
    tagline: 'Global Trade & Business Development',
    location: 'United Kingdom',
    description:
      'HighFive Global Ltd. is a UK-based international trading company involved in local distribution, import-export operations, and global sourcing solutions. The company focuses on building strong trade relationships between the UK and international markets.',
    banner: '/assets/company-highfive-global.jpg',
    slug: 'highfive-global-ltd',
    services: ['Import & Export', 'Local UK Distribution', 'International Trade Solutions', 'Product Sourcing', 'Procurement & Supply Chain Support', 'Business Development Services'],
    industries: ['Agro Products', 'Food & Beverage Products', 'FMCG Products', 'Household Goods', 'Personal Care Products', 'General Trading Products', 'Commercial Supplies'],
    markets: ['United Kingdom', 'Europe', 'Middle East', 'Asia', 'Africa'],
    icon: 'TrendingUp',
    color: 'from-[#00A8CC] to-[#0066AA]',
    email: null,
  },
];

export const partners = [
  { name: 'Air India', logo: '/assets/partners/air-india.png', alt: 'Air India cargo partner logo' },
  { name: 'IndiGo', logo: '/assets/partners/indigo.png', alt: 'IndiGo aviation cargo partner logo' },
  { name: 'Thai Airways', logo: '/assets/partners/thai-airways.png', alt: 'Thai Airways cargo partner logo' },
  { name: 'Air Arabia', logo: '/assets/partners/air-arabia.png', alt: 'Air Arabia logistics partner logo' },
  { name: 'Singapore Airlines', logo: '/assets/partners/singapore-airlines.png', alt: 'Singapore Airlines cargo partner logo' },
  { name: 'Kuwait Airways', logo: '/assets/partners/kuwait-airways.png', alt: 'Kuwait Airways cargo partner logo' },
  { name: 'SalamAir', logo: '/assets/partners/salamair.png', alt: 'SalamAir cargo partner logo' },
  { name: 'Oman Air', logo: '/assets/partners/oman-air.png', alt: 'Oman Air cargo partner logo' },
  { name: 'Uzbekistan Airways', logo: '/assets/partners/uzbekistan-airways.png', alt: 'Uzbekistan Airways cargo partner logo' },
  { name: 'Delhivery', logo: '/assets/partners/delhivery.png', alt: 'Delhivery logistics partner logo' },
  { name: 'Wipro', logo: '/assets/partners/wipro.png', alt: 'Wipro logistics partner logo' },
  { name: 'Shree Ji', logo: '/assets/partners/shree-ji.png', alt: 'Shree Ji logistics partner logo' },
  { name: 'Reliance', logo: '/assets/partners/reliance.png', alt: 'Reliance Industries logistics partner logo' },
  { name: 'SpiceJet', logo: '/assets/partners/spicejet.png', alt: 'SpiceJet cargo partner logo' },
  { name: 'Etihad Airways', logo: '/assets/partners/etihad.png', alt: 'Etihad Airways cargo partner logo' },
  { name: 'Korean Air', logo: '/assets/partners/korean-air.png', alt: 'Korean Air cargo partner logo' },
  { name: 'KisanMandi.com', logo: '/assets/partners/kisanmandi.png', alt: 'KisanMandi.com retail and wholesale partner logo' },
  { name: 'Dairy Craft', logo: '/assets/partners/dairy-craft.svg', alt: 'Dairy Craft dairy products partner logo' },
];

export const services = [
  {
    slug: 'air-freight',
    title: 'Air Freight',
    subtitle: 'Fast, Reliable & Time-Critical Cargo Delivery Worldwide',
    image: '/assets/service-air-freight.jpg',
    intro: 'When speed is paramount, our air freight services deliver. We partner with leading airlines to provide express, standard, and charter cargo solutions across the globe. From urgent documents to large equipment, we ensure your cargo reaches its destination safely and on time.',
    benefits: [
      { title: 'Express Delivery', desc: 'Same-day and next-day options for time-critical shipments.', icon: 'Plane' },
      { title: 'Global Coverage', desc: 'Access to 500+ airports across 50+ countries worldwide.', icon: 'Globe' },
      { title: 'Multi-Weight Options', desc: 'From small parcels to full charter aircraft capacity.', icon: 'Package' },
      { title: 'Secure Handling', desc: 'GPS-tracked cargo with tamper-proof sealing.', icon: 'Shield' },
    ],
    process: [
      { step: '01', title: 'Booking & Pickup', desc: 'Schedule your shipment and we collect from your location.' },
      { step: '02', title: 'Documentation', desc: 'We handle all air waybills, customs docs, and compliance.' },
      { step: '03', title: 'Air Transport', desc: 'Cargo loaded onto partner airline for fastest route.' },
      { step: '04', title: 'Delivery', desc: 'Door-to-door delivery at destination with real-time tracking.' },
    ],
    industries: ['Electronics', 'Automotive', 'E-commerce', 'Fashion', 'Aerospace', 'Manufacturing'],
    faqs: [
      { q: 'How fast is air freight delivery?', a: 'Depending on the destination, our express air freight delivers within 1-3 days, while standard air freight takes 3-7 days globally.' },
      { q: 'What is the maximum weight for air freight?', a: 'We handle shipments from 1kg to 100+ tons. For large cargo, our charter services provide dedicated aircraft solutions.' },
      { q: 'Do you provide door-to-door air freight?', a: 'Yes, we offer complete door-to-door air freight service including pickup, documentation, customs clearance, and final delivery.' },
    ],
    relatedSlugs: ['sea-freight', 'door-to-door-delivery', 'import-express'],
  },
  {
    slug: 'sea-freight',
    title: 'Sea Freight',
    subtitle: 'Cost-Effective Ocean Shipping for Global Trade',
    image: '/assets/service-sea-freight.jpg',
    intro: 'Our comprehensive sea freight solutions offer the most economical way to move large volumes across continents. Whether you need Full Container Load (FCL) or Less than Container Load (LCL), we provide reliable scheduling, competitive rates, and end-to-end management of your ocean cargo.',
    benefits: [
      { title: 'FCL & LCL Options', desc: 'Full container or shared space – flexibility for any volume.', icon: 'Ship' },
      { title: 'Global Routes', desc: 'Major trade lanes covering Asia, Europe, Americas, and Africa.', icon: 'Globe' },
      { title: 'Project Cargo', desc: 'Specialized handling for large-scale and heavy shipments.', icon: 'Package' },
      { title: 'Break Bulk', desc: 'Non-containerized cargo handling for specialized loads.', icon: 'Ship' },
    ],
    process: [
      { step: '01', title: 'Quote & Booking', desc: 'Receive a customized quote and confirm your shipment.' },
      { step: '02', title: 'Container Loading', desc: 'Cargo loaded at port with proper securing and documentation.' },
      { step: '03', title: 'Ocean Transit', desc: 'Vessel sails on scheduled route with GPS tracking.' },
      { step: '04', title: 'Port Clearance & Delivery', desc: 'Customs clearance and transport to final destination.' },
    ],
    industries: ['Automotive', 'FMCG', 'Industrial Equipment', 'Retail', 'Construction', 'Agriculture'],
    faqs: [
      { q: 'How long does sea freight take?', a: 'Transit times range from 15-45 days depending on origin, destination, and route. We provide accurate ETAs at booking.' },
      { q: 'What is the difference between FCL and LCL?', a: 'FCL (Full Container Load) gives you exclusive use of a container. LCL (Less than Container Load) shares container space with other shippers, ideal for smaller volumes.' },
      { q: 'Do you handle customs at ports?', a: 'Yes, our CHA team manages customs clearance at both origin and destination ports as part of our end-to-end service.' },
    ],
    relatedSlugs: ['air-freight', 'door-to-door-delivery', 'cha-services'],
  },
  {
    slug: 'door-to-door-delivery',
    title: 'Door to Door Delivery',
    subtitle: 'Complete Logistics From Pickup to Final Destination',
    image: '/assets/service-door-to-door.jpg',
    intro: "Our door-to-door delivery service takes the complexity out of logistics. We manage every step – from collecting goods at your premises to delivering them at the recipient's doorstep. With single-point accountability, real-time tracking, and hassle-free documentation, your cargo is in safe hands.",
    benefits: [
      { title: 'Single Point Contact', desc: 'One team handles everything from pickup to delivery.', icon: 'Truck' },
      { title: 'Real-Time Tracking', desc: 'Know exactly where your shipment is at every stage.', icon: 'TrendingUp' },
      { title: 'Hassle-Free Docs', desc: 'We manage all paperwork, permits, and customs forms.', icon: 'ClipboardCheck' },
      { title: 'Flexible Modes', desc: 'Air, sea, or land – we choose the best route for you.', icon: 'Globe' },
    ],
    process: [
      { step: '01', title: 'Pickup', desc: 'We collect your cargo from the specified location.' },
      { step: '02', title: 'Packaging & Docs', desc: 'Professional packing and documentation preparation.' },
      { step: '03', title: 'Transport & Customs', desc: 'Multi-modal transport with customs clearance handled.' },
      { step: '04', title: 'Final Delivery', desc: "Delivered to the recipient's doorstep with confirmation." },
    ],
    industries: ['E-commerce', 'Retail', 'Manufacturing', 'Personal Effects', 'Corporate Relocation', 'FMCG'],
    faqs: [
      { q: 'What does door-to-door service include?', a: 'It includes pickup from origin, packaging, documentation, customs clearance, international transport, and final delivery to the recipient.' },
      { q: 'Can I track my door-to-door shipment?', a: 'Yes, we provide full real-time tracking from pickup to final delivery through our digital platform.' },
      { q: 'Is insurance included?', a: 'Comprehensive cargo insurance is available and recommended for all door-to-door shipments.' },
    ],
    relatedSlugs: ['air-freight', 'sea-freight', 'by-road-line-haul'],
  },
  {
    slug: 'cha-services',
    title: 'Customs House Agent / CHA Services',
    subtitle: 'Expert Customs Clearance & Regulatory Compliance',
    image: '/assets/service-cha.jpg',
    intro: 'Navigating customs regulations can be complex and time-consuming. Our licensed Customs House Agents (CHA) simplify the entire process – from documentation and duty calculation to regulatory compliance and port clearance. With decades of experience, we ensure smooth, delay-free customs processing.',
    benefits: [
      { title: 'Documentation', desc: 'Complete import/export paperwork handled by experts.', icon: 'ClipboardCheck' },
      { title: 'Duty Optimization', desc: 'Legal strategies to minimize duties and tariffs.', icon: 'TrendingUp' },
      { title: 'HS Classification', desc: 'Accurate HS code assignment for your products.', icon: 'Shield' },
      { title: 'Compliance Consulting', desc: 'Regulatory advice for smooth international trade.', icon: 'Globe' },
    ],
    process: [
      { step: '01', title: 'Document Review', desc: 'Invoice, packing list, and permits verified.' },
      { step: '02', title: 'Customs Filing', desc: 'Shipping bill or bill of entry filed electronically.' },
      { step: '03', title: 'Examination', desc: 'Cargo inspection coordinated if required.' },
      { step: '04', title: 'Clearance', desc: 'Duty payment and customs release obtained.' },
    ],
    industries: ['Import/Export', 'Manufacturing', 'Retail', 'E-commerce', 'Automotive', 'Textile'],
    faqs: [
      { q: 'What documents are needed for customs clearance?', a: 'Typically invoice, packing list, bill of lading/airway bill, insurance certificate, and any required permits or certificates.' },
      { q: 'How long does customs clearance take?', a: 'With proper documentation, we achieve same-day or next-day clearance at major Indian ports.' },
      { q: 'Do you handle duty drawback claims?', a: 'Yes, we process duty drawback claims and export incentives as part of our CHA services.' },
    ],
    relatedSlugs: ['air-freight', 'sea-freight', 'import-express'],
  },
  {
    slug: 'domestic-priority',
    title: 'Domestic Priority',
    subtitle: 'Fast & Reliable Domestic Delivery Across India',
    image: '/assets/service-domestic-priority.jpg',
    intro: 'Our Domestic Priority service offers expedited delivery across every corner of India. Whether you need next-day delivery to metro cities or 2-3 day delivery to tier-2 and tier-3 locations, our priority network ensures your shipments move fast without compromising safety.',
    benefits: [
      { title: 'Next-Day Delivery', desc: 'Overnight delivery to all major Indian cities.', icon: 'Zap' },
      { title: 'Pan-India Coverage', desc: 'Delivery to 19,000+ pin codes across India.', icon: 'Globe' },
      { title: 'Real-Time Tracking', desc: 'Track every domestic shipment in real-time.', icon: 'TrendingUp' },
      { title: 'COD Available', desc: 'Cash on delivery option for commercial shipments.', icon: 'Package' },
    ],
    process: [
      { step: '01', title: 'Priority Pickup', desc: 'Same-day collection from your location.' },
      { step: '02', title: 'Express Transit', desc: 'Routed through priority lane network.' },
      { step: '03', title: 'Hub Processing', desc: 'Fast sorting and dispatch at regional hubs.' },
      { step: '04', title: 'Priority Delivery', desc: 'Next-day or 48-hour delivery with confirmation.' },
    ],
    industries: ['E-commerce', 'B2B', 'Healthcare', 'Banking', 'Legal', 'Manufacturing'],
    faqs: [
      { q: 'How fast is Domestic Priority delivery?', a: 'We offer next-day delivery to metros and major cities, and 48-72 hour delivery to tier-2 and tier-3 cities across India.' },
      { q: 'Do you deliver to remote areas?', a: 'Yes, we cover 19,000+ pin codes across India including remote and rural locations.' },
      { q: 'Is there a weight limit?', a: 'Domestic Priority accepts shipments from 500g up to 100kg. For heavier cargo, our By Road / Line Haul service is recommended.' },
    ],
    relatedSlugs: ['door-to-door-delivery', 'by-road-line-haul', 'by-train'],
  },
  {
    slug: 'import-express',
    title: 'Import Express',
    subtitle: 'Fast-Track Import Solutions from Global Origins',
    image: '/assets/service-import-express.jpg',
    intro: 'Our Import Express service simplifies and accelerates the process of bringing goods into India. From supplier pickup anywhere in the world to fast-track customs clearance and final delivery, we manage the entire import chain.',
    benefits: [
      { title: 'Fast Clearance', desc: 'Express customs clearance with pre-filed documentation.', icon: 'Zap' },
      { title: 'Global Pickup', desc: 'Collection from your supplier anywhere in the world.', icon: 'Globe' },
      { title: 'Duty Guidance', desc: 'Expert advice on HS codes, duties, and tax optimization.', icon: 'ClipboardCheck' },
      { title: 'Door Delivery', desc: 'Direct delivery to your warehouse or facility in India.', icon: 'Truck' },
    ],
    process: [
      { step: '01', title: 'Supplier Coordination', desc: 'We contact your overseas supplier for pickup arrangement.' },
      { step: '02', title: 'International Transit', desc: 'Priority air or sea freight to India.' },
      { step: '03', title: 'Import Clearance', desc: 'Fast-track customs clearance with our CHA team.' },
      { step: '04', title: 'Final Delivery', desc: 'Delivered to your Indian address with full documentation.' },
    ],
    industries: ['Manufacturing', 'Retail', 'Automotive', 'Electronics', 'Textile', 'FMCG'],
    faqs: [
      { q: 'How fast can you clear imports?', a: 'With proper documentation, we achieve same-day or next-day customs clearance at all major Indian ports and airports.' },
      { q: 'Do I need an IEC for import express?', a: 'Yes, an Import Export Code (IEC) is mandatory for commercial imports into India. We can guide you through the IEC application process.' },
      { q: 'Can you handle supplier payments abroad?', a: 'We can coordinate with your bank for Letter of Credit (LC) and other payment arrangements with international suppliers.' },
    ],
    relatedSlugs: ['cha-services', 'air-freight', 'sea-freight'],
  },
  {
    slug: 'international-marketing',
    title: 'International Marketing',
    subtitle: 'Expand Your Business Across Global Markets',
    image: '/assets/service-international-marketing.jpg',
    intro: 'Beyond logistics, we help businesses grow internationally. Our international marketing service connects you with global trade opportunities, market insights, and strategic partnerships. Whether you are exploring new export markets or seeking import suppliers, our team provides the intelligence and connections you need.',
    benefits: [
      { title: 'Market Research', desc: 'Insights into target markets and competition.', icon: 'TrendingUp' },
      { title: 'Trade Connections', desc: 'Network of verified buyers and suppliers globally.', icon: 'Globe' },
      { title: 'Growth Strategy', desc: 'Customized market entry and expansion plans.', icon: 'Shield' },
      { title: 'Regulatory Guidance', desc: 'Navigate foreign trade regulations confidently.', icon: 'ClipboardCheck' },
    ],
    process: [
      { step: '01', title: 'Consultation', desc: 'Understand your business goals and target markets.' },
      { step: '02', title: 'Research', desc: 'Market analysis and opportunity identification.' },
      { step: '03', title: 'Strategy', desc: 'Customized international growth plan created.' },
      { step: '04', title: 'Execution', desc: 'Ongoing support for market entry and expansion.' },
    ],
    industries: ['Export/Import Trading', 'Manufacturing', 'Agriculture', 'Textile', 'Consumer Goods', 'Technology'],
    faqs: [
      { q: 'How can you help my export business?', a: 'We connect you with verified international buyers, provide market intelligence, and handle the logistics – all under one roof.' },
      { q: 'Do you work with startups?', a: 'Yes, we help businesses of all sizes expand internationally with scalable solutions.' },
      { q: 'Which markets do you cover?', a: 'We have active trade networks across UAE, Singapore, Europe, Africa, USA, UK, and Southeast Asia.' },
    ],
    relatedSlugs: ['global-network', 'cha-services', 'air-freight'],
  },
  {
    slug: 'global-network',
    title: 'Global Network',
    subtitle: '50+ Countries Connected, One Trusted Partner',
    image: '/assets/service-global-network.jpg',
    intro: 'With direct offices in India and UAE, and a trusted partner network spanning over 50 countries, Highority provides truly global logistics coverage. Our strategically located hubs and established relationships with local carriers ensure seamless cargo movement across continents.',
    benefits: [
      { title: 'Direct Offices', desc: 'Owned offices in India (Zirakpur, Ahmedabad, Delhi, Jaipur) and UAE (Dubai).', icon: 'Globe' },
      { title: '50+ Countries', desc: 'Comprehensive coverage across six continents.', icon: 'Globe' },
      { title: 'Local Expertise', desc: 'Partners with deep local market knowledge.', icon: 'Shield' },
      { title: 'Unified Tracking', desc: 'Single platform to track across all destinations.', icon: 'TrendingUp' },
    ],
    process: [
      { step: '01', title: 'Origin Handling', desc: 'Cargo collected and processed at origin office.' },
      { step: '02', title: 'International Transit', desc: 'Moved via optimal global route.' },
      { step: '03', title: 'Destination Clearance', desc: 'Customs and regulatory clearance at destination.' },
      { step: '04', title: 'Final Mile', desc: 'Local partner delivers to final destination.' },
    ],
    industries: ['All Industries', 'Global Trade', 'Multinational Corporations', 'SME Exporters', 'E-commerce', 'Project Cargo'],
    faqs: [
      { q: 'Which countries do you serve?', a: 'We serve 50+ countries including UAE, Singapore, USA, UK, Germany, Canada, Australia, Thailand, Kuwait, Hong Kong, Brazil, and more.' },
      { q: 'Do you have offices outside India?', a: 'Yes, we have a direct office in Dubai, UAE as Highority Impex Trading LLC, in addition to our Indian offices.' },
      { q: 'How do I track international shipments?', a: 'All shipments are tracked through our unified digital platform, regardless of destination country.' },
    ],
    relatedSlugs: ['air-freight', 'sea-freight', 'international-marketing'],
  },
  {
    slug: 'by-road-line-haul',
    title: 'By Road / Line Haul',
    subtitle: 'Intercity & Long-Distance Road Cargo Transportation',
    image: '/assets/service-by-road.jpg',
    intro: 'Our By Road / Line Haul service provides efficient intercity and long-distance cargo movement across India and beyond. With a modern fleet of container trucks, flatbeds, and specialized vehicles, we handle scheduled cargo delivery with precision. Ideal for manufacturers, distributors, and businesses that need reliable road logistics connecting major cities and industrial zones.',
    benefits: [
      { title: 'Pan-India Coverage', desc: 'Connected to all major cities and industrial corridors.', icon: 'Truck' },
      { title: 'Scheduled Delivery', desc: 'Fixed routes with reliable pickup and delivery windows.', icon: 'Zap' },
      { title: 'FTL & LTL Options', desc: 'Full truckload or part-load based on your cargo volume.', icon: 'Package' },
      { title: 'GPS Tracking', desc: 'Real-time vehicle tracking on every route.', icon: 'TrendingUp' },
    ],
    process: [
      { step: '01', title: 'Booking & Pickup', desc: 'Schedule your line haul and we collect from your facility.' },
      { step: '02', title: 'Loading & Securing', desc: 'Cargo safely loaded and secured for transit.' },
      { step: '03', title: 'Line Haul Transit', desc: 'Long-distance transport via optimized highway routes.' },
      { step: '04', title: 'On-Time Delivery', desc: 'Delivered to destination hub or final address.' },
    ],
    industries: ['Manufacturing', 'FMCG Distribution', 'Automotive', 'Retail', 'E-commerce', 'Construction'],
    faqs: [
      { q: 'What routes do you cover?', a: 'We cover all major highway corridors including Delhi-Mumbai, Mumbai-Chennai, Delhi-Kolkata, and pan-India connectivity.' },
      { q: 'How long does line haul delivery take?', a: 'Metro to metro: 1-3 days. Longer routes: 3-5 days depending on distance and route conditions.' },
      { q: 'Do you provide part-load (LTL) service?', a: 'Yes, our LTL service allows you to share truck space, reducing costs for smaller shipments.' },
    ],
    relatedSlugs: ['domestic-priority', 'by-train', 'door-to-door-delivery'],
  },
  {
    slug: 'by-train',
    title: 'By Train',
    subtitle: 'Cost-Effective Rail Freight for Bulk Cargo',
    image: '/assets/service-by-train.jpg',
    intro: "Our rail freight service leverages India's extensive railway network to move bulk cargo economically across the country. With dedicated freight corridors, container trains, and secure loading facilities, we provide a greener, more cost-effective alternative to road transport for large-volume shipments.",
    benefits: [
      { title: 'Cost-Effective', desc: 'Up to 40% savings compared to road freight for bulk cargo.', icon: 'TrainFront' },
      { title: 'Large Capacity', desc: 'Move hundreds of tons in a single shipment.', icon: 'Package' },
      { title: 'Eco-Friendly', desc: 'Lower carbon footprint compared to road transport.', icon: 'Globe' },
      { title: 'Secure Transport', desc: 'Sealed container movement with minimal handling.', icon: 'Shield' },
    ],
    process: [
      { step: '01', title: 'Cargo Assessment', desc: 'Volume, weight, and route planning for rail transport.' },
      { step: '02', title: 'Container Loading', desc: 'Cargo loaded into sealed rail containers at yard.' },
      { step: '03', title: 'Rail Transit', desc: 'Moved via dedicated freight corridors across India.' },
      { step: '04', title: 'Unloading & Delivery', desc: 'Cargo unloaded and delivered to your facility.' },
    ],
    industries: ['Steel & Metals', 'Agriculture', 'Coal & Mining', 'FMCG', 'Construction Materials', 'Automotive Parts'],
    faqs: [
      { q: 'How fast is rail freight compared to road?', a: 'Rail freight is comparable for long distances (500+ km) and often faster on dedicated freight corridors.' },
      { q: 'What is the minimum cargo volume for rail?', a: 'Rail freight becomes cost-effective for shipments above 5 tons or full container loads (FCL).' },
      { q: 'Do you handle first-mile and last-mile?', a: 'Yes, we provide complete logistics including pickup from your location and delivery to the final destination.' },
    ],
    relatedSlugs: ['by-road-line-haul', 'domestic-priority', 'sea-freight'],
  },
  {
    slug: 'warehousing-distribution',
    title: 'Warehousing & Distribution',
    subtitle: 'Smart Storage, Inventory & Distribution Solutions',
    image: '/assets/service-warehousing.jpg',
    intro: 'At Highority Group, we understand the critical role warehousing and distribution play in the freight forwarding and supply chain industry. Our warehousing solutions provide secure storage, inventory control, cargo handling, and efficient order fulfillment. Combined with our distribution network, we help businesses streamline operations, reduce transit times, and improve customer satisfaction.',
    benefits: [
      { title: 'Secure Storage', desc: 'Modern warehousing facilities with 24/7 security and climate control options.', icon: 'Warehouse' },
      { title: 'Inventory Control', desc: 'Real-time inventory tracking and management systems.', icon: 'ClipboardCheck' },
      { title: 'Efficient Distribution', desc: 'Pan-India distribution network for faster delivery.', icon: 'Truck' },
      { title: 'Order Fulfillment', desc: 'Complete pick, pack, and ship services.', icon: 'Package' },
    ],
    process: [
      { step: '01', title: 'Cargo Receipt', desc: 'Goods received, inspected, and logged into inventory system.' },
      { step: '02', title: 'Storage & Management', desc: 'Systematic storage with real-time inventory tracking.' },
      { step: '03', title: 'Order Processing', desc: 'Pick, pack, and prepare orders for dispatch.' },
      { step: '04', title: 'Distribution', desc: 'Delivered via our network to final destination.' },
    ],
    industries: ['Retail', 'FMCG', 'Manufacturing', 'Electronics', 'Automotive', 'Import & Export', 'E-commerce', 'International Trade'],
    faqs: [
      { q: 'What warehousing services do you offer?', a: 'We offer secure storage, inventory management, order fulfillment, pick & pack, cross-docking, and distribution services across India.' },
      { q: 'Do you provide real-time inventory tracking?', a: 'Yes, our digital inventory management system provides real-time tracking and reporting.' },
      { q: 'Can you handle e-commerce fulfillment?', a: 'Absolutely. We provide complete e-commerce fulfillment including storage, order processing, and last-mile delivery.' },
    ],
    relatedSlugs: ['domestic-priority', 'by-road-line-haul', 'door-to-door-delivery'],
  },
];
